remove perm gem atlassian only supports jdk8

diff --git a/templates/default/setenv.sh.erb b/templates/default/setenv.sh.erb
--- a/templates/default/setenv.sh.erb
+++ b/templates/default/setenv.sh.erb
@@ -1,23 +1,13 @@
-#
-#  Dynamically generated by Chef on <%= node["fqdn"] %>
-#  Local modifications will be overwritten by Chef.
-#
-
+#!/bin/sh
 #
 # One way to set the Bamboo HOME path is here via this variable.  Simply uncomment it and set a valid path like /bamboo/home.  You can of course set it outside in the command terminal.  That will also work.
 #
-#BAMBOO_HOME="<%= node['bamboo']['data_dir'] %>"
-
-#
-# Sometimes required to select
-#
-CATALINA_OPTS="${CATALINA_OPTS} <%= node['bamboo']['catalina']['opts'] %>"
-export CATALINA_OPTS
+#BAMBOO_HOME=""
 
 #
 #  Occasionally Atlassian Support may recommend that you set some specific JVM arguments.  You can use this variable below to do that.
 #
-JVM_SUPPORT_RECOMMENDED_ARGS="<%= node['bamboo']['jvm']['support_args'] %>"
+JVM_SUPPORT_RECOMMENDED_ARGS=""
 
 #
 # The following 2 settings control the minimum and maximum given to the Bamboo Java virtual machine.  In larger Bamboo instances, the maximum amount will need to be increased.
@@ -33,7 +23,7 @@ JVM_REQUIRED_ARGS=""
 #
 # Needs to be set on the bamboo server to disable agent capability detection
 #
-JVM_AGENT_AUTO_CAP_DET="-DDISABLE_AGENT_AUTO_CAPABILITY_DETECTION=<%= node[:bamboo][:agent][:disable_agent_auto_capability_detection] %>"
+JVM_AGENT_AUTO_CAP_DET="-DDISABLE_AGENT_AUTO_CAPABILITY_DETECTION=<%= node['bamboo']['agent']['disable_agent_auto_capability_detection'] %>"
 
 #-----------------------------------------------------------------------------------
 #
@@ -43,42 +33,28 @@ JVM_AGENT_AUTO_CAP_DET="-DDISABLE_AGENT_AUTO_CAPABILITY_DETECTION=<%= node[:bamb
 
 PRGDIR=`dirname "$0"`
 cat "${PRGDIR}"/bamboobanner.txt
-export CATALINA_PID=<%= node[:bamboo][:data_dir] %>/<%= node[:bamboo][:name] %>.pid
 
-#BAMBOO_HOME_MINUSD=""
-#if [ "$BAMBOO_HOME" != "" ]; then
-#    echo $BAMBOO_HOME | grep -q " "
-#    if [ $? -eq 0 ]; then
-#	    echo ""
-#	    echo "----------------------------------------------------------------------------------------------------------------------"
-#		echo "   WARNING : You cannot have a BAMBOO_HOME environment variable set with spaces in it.  This variable is being ignored"
-#	    echo "----------------------------------------------------------------------------------------------------------------------"
-#   else
-#		BAMBOO_HOME_MINUSD=-Dbamboo.home=$BAMBOO_HOME
-#   fi
-#i
-
-JAVA_OPTS="-Xms${JVM_MINIMUM_MEMORY} -Xmx${JVM_MAXIMUM_MEMORY} ${JAVA_OPTS} ${JVM_REQUIRED_ARGS} ${JVM_SUPPORT_RECOMMENDED_ARGS} ${JVM_AGENT_AUTO_CAP_DET}" #${BAMBOO_HOME_MINUSD}"
-
-
-# Perm Gen size needs to be increased if encountering OutOfMemoryError: PermGen problems. Specifying PermGen size is not valid on IBM JDKs
-BAMBOO_MAX_PERM_SIZE="<%= node['bamboo']['jvm']['maximum_permgen'] %>"
-if [ -f "${PRGDIR}/permgen.sh" ]; then
-    echo "Detecting JVM PermGen support..."
-    . "${PRGDIR}/permgen.sh"
-    if [ $JAVA_PERMGEN_SUPPORTED = "true" ]; then
-        echo "PermGen switch is supported. Setting to ${BAMBOO_MAX_PERM_SIZE}"
-        JAVA_OPTS="-XX:MaxPermSize=${BAMBOO_MAX_PERM_SIZE} ${JAVA_OPTS}"
-    else
-        echo "PermGen switch is NOT supported and will NOT be set automatically."
-    fi
+BAMBOO_HOME_MINUSD=""
+if [ "$BAMBOO_HOME" != "" ]; then
+    echo $BAMBOO_HOME | grep -q " "
+    if [ $? -eq 0 ]; then
+	    echo ""
+	    echo "----------------------------------------------------------------------------------------------------------------------"
+		echo "   WARNING : You cannot have a BAMBOO_HOME environment variable set with spaces in it.  This variable is being ignored"
+	    echo "----------------------------------------------------------------------------------------------------------------------"
+   else
+		BAMBOO_HOME_MINUSD=-Dbamboo.home=$BAMBOO_HOME
+   fi
 fi
 
+JAVA_OPTS="-Xms${JVM_MINIMUM_MEMORY} -Xmx${JVM_MAXIMUM_MEMORY} ${JAVA_OPTS} ${JVM_REQUIRED_ARGS} ${JVM_SUPPORT_RECOMMENDED_ARGS} ${JVM_AGENT_AUTO_CAP_DET} ${BAMBOO_HOME_MINUSD}"
+
+JAVA_OPTS=$(echo "$JAVA_OPTS" | sed -e 's/\s*$//' -e 's/^\s*//')
 export JAVA_OPTS
 
 echo ""
-echo "If you encounter issues starting or stopping Bamboo Standalone Edition, please see the Troubleshooting guide at https://confluence.atlassian.com/display/BAMBOO/Bamboo+installation+guide"
+echo "If you encounter issues starting or stopping Bamboo Server, please see the Troubleshooting guide at https://confluence.atlassian.com/display/BAMBOO/Installing+and+upgrading+Bamboo"
 echo ""
-#if [ "$BAMBOO_HOME_MINUSD" != "" ]; then
-#    echo "Using BAMBOO_HOME:       $BAMBOO_HOME"
-#fi
+if [ "$BAMBOO_HOME_MINUSD" != "" ]; then
+    echo "Using BAMBOO_HOME:       $BAMBOO_HOME"
+fi
